version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: sleep infinity
    depends_on:
      - postgres
    env_file:
      - ./backend/.env/dev.injected.env
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    image: holiplan_backend_dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/src
      - backend_venv:/app/env
  postgres:
    env_file:
      - ./postgres/.env/dev.injected.env
    image: postgres:14.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}
  backend_venv: {}